### ISSUE TITLE
Stop using fields, use auto-implemented properties

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Simplified#112]
Due to https://github.com/Starcounter/level1/issues/4579.

Sample error with fields around:

> error SCERR4307: ScErrFieldInDatabaseType (SCERR4307): Database types can not declare instance fields. Class Concepts.Ring1.SystemX.SocietyObjectsWorkspace define a field: Ring. Use instead auto-implemented properties to define database accessors.

**Comment by per-samuelsson** [comment]
Doing some testing, and are currently considering this: https://github.com/Starcounter/level1/issues/4579#issuecomment-379652058

**Comment by per-samuelsson** [comment]
@miyconst 

I don't seem to have write access to this repo so can't assign this to me, but I'll fix it, because it's a showstopper to have TC run later tests, so I'll provide you a PR to merge later.

**Comment by miyconst** [comment]
@per-samuelsson you should have access to the repository now.

**Comment by per-samuelsson** [comment]
Just one question @miyconst: fields in `Simplified.Ring3.Address` are declared protected. We can only keep support for *private* fields. If I change to private, subtypes will no longer have direct access to those, is that ok still?

**Comment by miyconst** [comment]
>... We can only keep support for private fields. If I change to private, subtypes will no longer have direct access to those, is that ok still?

That should be fine, cc @warpech, @LarsTjernstrom.

**Comment by per-samuelsson** [comment]
> Just one question @miyconst: fields in `Simplified.Ring3.Address` are declared protected. We can only keep support for *private* fields. If I change to private, subtypes will no longer have direct access to those, is that ok still?

Got a go from @miyconst off-tracker, and going with this approach.

**Comment by per-samuelsson** [comment]
Done. Merged from #113.
