### ISSUE TITLE
Remove fields from Gender.cs

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Simplified#15]
We should remove the `MaleName` and `FemaleName` fields if they are unused from the [public Gender class](https://github.com/StarcounterSamples/Simplified/blob/master/Ring2/Gender.cs). These fields are not alone the complete scope of Gender, hence it should be removed.

**Comment by miyconst** [comment]
Well, the scope is enough for 99%, unless we have some strange snails and worms in our `Someone` table :D.

Those values are used by one of our customers, but I agree, better to remove it, not everyone uses English.

**Comment by ubbeK** [comment]
Archive
